default_context:
  project_name: 'Kalaam'
  project_slug: 'kalaam'
  domain_main: 'kalaam.now.sh'
  domain_staging: 'stag.kalaam.now.sh'
  docker_swarm_stack_name_main: 'kalaam'
  docker_swarm_stack_name_staging: 'stag-kalaam'
  secret_key: '12345'
  first_superuser: 'admin@kalaam.now.sh'
  first_superuser_password: '12345'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.kalaam.now.sh", "https://stag.kalaam.now.sh", "https://kalaam.now.sh", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@kalaam.now.sh'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@kalaam.now.sh'
  pgadmin_default_user_password: '12345'
  traefik_constraint_tag: 'kalaam.now.sh'
  traefik_constraint_tag_staging: 'stag.kalaam.now.sh'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
